// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGnEWXhZ8Jm1mUE7vMJQIRBvaJQDuT9KE',
    appId: '1:399872609465:web:27a3fdbc303c7282d29f68',
    messagingSenderId: '399872609465',
    projectId: 'flutter-sample-app-cidf23aa022',
    authDomain: 'flutter-sample-app-cidf23aa022.firebaseapp.com',
    storageBucket: 'flutter-sample-app-cidf23aa022.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdKaaohTaXQc9SurbU5BiMue5-wk35Tkc',
    appId: '1:399872609465:android:9ff600f83eebd455d29f68',
    messagingSenderId: '399872609465',
    projectId: 'flutter-sample-app-cidf23aa022',
    storageBucket: 'flutter-sample-app-cidf23aa022.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX5_QDgURGLTPjUzPRR1L3pkwMEuEgNQY',
    appId: '1:399872609465:ios:160c3a1dd093efa0d29f68',
    messagingSenderId: '399872609465',
    projectId: 'flutter-sample-app-cidf23aa022',
    storageBucket: 'flutter-sample-app-cidf23aa022.firebasestorage.app',
    iosBundleId: 'com.example.sample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX5_QDgURGLTPjUzPRR1L3pkwMEuEgNQY',
    appId: '1:399872609465:ios:160c3a1dd093efa0d29f68',
    messagingSenderId: '399872609465',
    projectId: 'flutter-sample-app-cidf23aa022',
    storageBucket: 'flutter-sample-app-cidf23aa022.firebasestorage.app',
    iosBundleId: 'com.example.sample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGnEWXhZ8Jm1mUE7vMJQIRBvaJQDuT9KE',
    appId: '1:399872609465:web:f005977928129d66d29f68',
    messagingSenderId: '399872609465',
    projectId: 'flutter-sample-app-cidf23aa022',
    authDomain: 'flutter-sample-app-cidf23aa022.firebaseapp.com',
    storageBucket: 'flutter-sample-app-cidf23aa022.firebasestorage.app',
  );
}
